CREATE DATABASE IF NOT EXISTS orfeoNG_db
    CHARACTER SET utf8
    COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS 'orfeo'@'%' IDENTIFIED BY 'orfeo123';
GRANT ALL PRIVILEGES ON orfeoNG_db.* TO 'orfeo'@'%';
FLUSH PRIVILEGES;
