server {
    listen 80;
    server_name _;
    root /app/api/web;
    index index.php;

    client_max_body_size 64M;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PHP_VALUE "upload_max_filesize = 64M \n post_max_size = 64M";
        include fastcgi_params;
    }

    location ~ /\.(ht|git) {
        deny all;
    }
}
